apiVersion: v1
kind: Service
metadata:
  name: tetris-service
spec:
  type: NodePort
  selector:
    app: tetris
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30081  # External port to access in browser
